# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/szikar/Fejlesztes/Projekt/Eric6GTD/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/ico/mail-archive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalFrame = QtWidgets.QFrame(self.centralWidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(0, 20, 221, 511))
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.horizontalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.verticalFrame = QtWidgets.QFrame(self.centralWidget)
        self.verticalFrame.setGeometry(QtCore.QRect(220, 20, 591, 511))
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 587, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 816, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFajl = QtWidgets.QMenu(self.menuBar)
        self.menuFajl.setObjectName("menuFajl")
        self.menuSzerkesztes = QtWidgets.QMenu(self.menuBar)
        self.menuSzerkesztes.setObjectName("menuSzerkesztes")
        self.menuSugo = QtWidgets.QMenu(self.menuBar)
        self.menuSugo.setObjectName("menuSugo")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.Options = QtWidgets.QToolBar(MainWindow)
        self.Options.setMovable(False)
        self.Options.setObjectName("Options")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.Options)
        self.actionKilepes = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/ico/system-log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKilepes.setIcon(icon1)
        self.actionKilepes.setObjectName("actionKilepes")
        self.actionMasolas = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/ico/edit-copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMasolas.setIcon(icon2)
        self.actionMasolas.setObjectName("actionMasolas")
        self.actionKivagas = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/ico/edit-cut-3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKivagas.setIcon(icon3)
        self.actionKivagas.setObjectName("actionKivagas")
        self.actionBeillesztes = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/ico/edit-paste-3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeillesztes.setIcon(icon4)
        self.actionBeillesztes.setObjectName("actionBeillesztes")
        self.actionNevjegy = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/ico/help-about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNevjegy.setIcon(icon5)
        self.actionNevjegy.setObjectName("actionNevjegy")
        self.actionUj = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/ico/document-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUj.setIcon(icon6)
        self.actionUj.setObjectName("actionUj")
        self.actionMentes = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/ico/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMentes.setIcon(icon7)
        self.actionMentes.setObjectName("actionMentes")
        self.actionMentes_maskent = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/ico/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMentes_maskent.setIcon(icon8)
        self.actionMentes_maskent.setObjectName("actionMentes_maskent")
        self.actionTorles = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/ico/edit-delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTorles.setIcon(icon9)
        self.actionTorles.setObjectName("actionTorles")
        self.menuFajl.addAction(self.actionUj)
        self.menuFajl.addAction(self.actionMentes)
        self.menuFajl.addAction(self.actionMentes_maskent)
        self.menuFajl.addAction(self.actionTorles)
        self.menuFajl.addSeparator()
        self.menuFajl.addAction(self.actionKilepes)
        self.menuSzerkesztes.addAction(self.actionMasolas)
        self.menuSzerkesztes.addAction(self.actionKivagas)
        self.menuSzerkesztes.addAction(self.actionBeillesztes)
        self.menuSugo.addAction(self.actionNevjegy)
        self.menuBar.addAction(self.menuFajl.menuAction())
        self.menuBar.addAction(self.menuSzerkesztes.menuAction())
        self.menuBar.addAction(self.menuSugo.menuAction())
        self.Options.addAction(self.actionUj)
        self.Options.addAction(self.actionMentes)
        self.Options.addAction(self.actionMentes_maskent)
        self.Options.addAction(self.actionMasolas)
        self.Options.addAction(self.actionKivagas)
        self.Options.addAction(self.actionBeillesztes)
        self.Options.addAction(self.actionKilepes)
        self.Options.addSeparator()

        self.retranslateUi(MainWindow)
        self.actionKilepes.triggered.connect(MainWindow.close)
        self.actionMasolas.triggered.connect(self.textEdit.copy)
        self.actionKivagas.triggered.connect(self.textEdit.cut)
        self.actionBeillesztes.triggered.connect(self.textEdit.paste)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GTD by Linux"))
        self.menuFajl.setTitle(_translate("MainWindow", "Fájl"))
        self.menuSzerkesztes.setTitle(_translate("MainWindow", "Szerkesztés"))
        self.menuSugo.setTitle(_translate("MainWindow", "Súgó"))
        self.Options.setWindowTitle(_translate("MainWindow", "Options"))
        self.actionKilepes.setText(_translate("MainWindow", "Kilépés"))
        self.actionMasolas.setText(_translate("MainWindow", "Másolás"))
        self.actionKivagas.setText(_translate("MainWindow", "Kivágás"))
        self.actionBeillesztes.setText(_translate("MainWindow", "Beillesztés"))
        self.actionNevjegy.setText(_translate("MainWindow", "Névjegy"))
        self.actionUj.setText(_translate("MainWindow", "Új"))
        self.actionMentes.setText(_translate("MainWindow", "Mentés"))
        self.actionMentes_maskent.setText(_translate("MainWindow", "Mentés másként"))
        self.actionTorles.setText(_translate("MainWindow", "Törlés"))

import ikonok_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

